### ISSUE TITLE
Building wheel for lxml (setup.py) ... error

### ISSUE THREAD

**Issue by IlirBajrami** [Yenthe666/InstallScript#243]
hi there. imtrying to install odoo in DigitalOcean droplet using your script in ubuntu 20.04.
after the script finished installing i tried accessing odoo at port 8069 but didnt get any result then i scrolled up and noticed 2 errors:

` ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6kpb7w57/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6kpb7w57/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-bx3ifawh
       cwd: /tmp/pip-install-6kpb7w57/lxml/
  Complete output (84 lines):
  Building lxml version 4.3.2.
  Building without Cython.
  Using build configuration of libxslt 1.1.34
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/builder.py -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/sax.py -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/cssselect.py -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/__init__.py -> build/lib.linux-x86_64-3.8/lxml
  creating build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-3.8/lxml/includes
  creating build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/builder.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/clean.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/diff.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/defs.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-3.8/lxml/html
  creating build/lib.linux-x86_64-3.8/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-3.8/lxml/isoschematron
  copying src/lxml/etree.h -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/etree_api.h -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/__init__.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-3.8/lxml/includes
  creating build/lib.linux-x86_64-3.8/lxml/isoschematron/resources
  creating build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/rng
  creating build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl
  creating build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/src
  creating build/temp.linux-x86_64-3.8/src/lxml
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/usr/include/libxml2 -Isrc -Isrc/lxml/includes -I/usr/include/python3.8 -c src/lxml/etree.c -o build/temp.linux-x86_64-3.8/src/lxml/etree.o -w
  x86_64-linux-gnu-gcc: fatal error: Killed signal terminated program cc1
  compilation terminated.
  Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  creating tmp
  cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /tmp/xmlXPathInituhszi0mm.c -o tmp/xmlXPathInituhszi0mm.o
  cc tmp/xmlXPathInituhszi0mm.o -lxml2 -o a.out
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for lxml `

and below this one:

`ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6kpb7w57/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6kpb7w57/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0lsx7d1q/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/lxml
         cwd: /tmp/pip-install-6kpb7w57/lxml/
    Complete output (83 lines):
    Building lxml version 4.3.2.
    Building without Cython.
    Using build configuration of libxslt 1.1.34
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/lxml
    copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-3.8/lxml
    copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-3.8/lxml
    copying src/lxml/builder.py -> build/lib.linux-x86_64-3.8/lxml
    copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-3.8/lxml
    copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-3.8/lxml
    copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-3.8/lxml
    copying src/lxml/sax.py -> build/lib.linux-x86_64-3.8/lxml
    copying src/lxml/cssselect.py -> build/lib.linux-x86_64-3.8/lxml
    copying src/lxml/__init__.py -> build/lib.linux-x86_64-3.8/lxml
    creating build/lib.linux-x86_64-3.8/lxml/includes
    copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-3.8/lxml/includes
    creating build/lib.linux-x86_64-3.8/lxml/html
    copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-3.8/lxml/html
    copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-3.8/lxml/html
    copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-3.8/lxml/html
    copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-3.8/lxml/html
    copying src/lxml/html/builder.py -> build/lib.linux-x86_64-3.8/lxml/html
    copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-3.8/lxml/html
    copying src/lxml/html/clean.py -> build/lib.linux-x86_64-3.8/lxml/html
    copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-3.8/lxml/html
    copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-3.8/lxml/html
    copying src/lxml/html/diff.py -> build/lib.linux-x86_64-3.8/lxml/html
    copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-3.8/lxml/html
    copying src/lxml/html/defs.py -> build/lib.linux-x86_64-3.8/lxml/html
    copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-3.8/lxml/html
    creating build/lib.linux-x86_64-3.8/lxml/isoschematron
    copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-3.8/lxml/isoschematron
    copying src/lxml/etree.h -> build/lib.linux-x86_64-3.8/lxml
    copying src/lxml/etree_api.h -> build/lib.linux-x86_64-3.8/lxml
    copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-3.8/lxml
    copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-3.8/lxml
    copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
    copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
    copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
    copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
    copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
    copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
    copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
    copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
    copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
    copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
    copying src/lxml/includes/__init__.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
    copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
    copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
    copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
    copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
    copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
    copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-3.8/lxml/includes
    copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-3.8/lxml/includes
    creating build/lib.linux-x86_64-3.8/lxml/isoschematron/resources
    creating build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/rng
    copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/rng
    creating build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl
    creating build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/src
    creating build/temp.linux-x86_64-3.8/src/lxml
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/usr/include/libxml2 -Isrc -Isrc/lxml/includes -I/usr/include/python3.8 -c src/lxml/etree.c -o build/temp.linux-x86_64-3.8/src/lxml/etree.o -w
    x86_64-linux-gnu-gcc: fatal error: Killed signal terminated program cc1
    compilation terminated.
    Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /tmp/xmlXPathInitlyme5kmf.c -o tmp/xmlXPathInitlyme5kmf.o
    cc tmp/xmlXPathInitlyme5kmf.o -lxml2 -o a.out
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6kpb7w57/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6kpb7w57/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0lsx7d1q/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/lxml Check the logs for full command output.`

how to fix this issue pls?

**Comment by Yenthe666** [comment]
Did you use a very small droplet? Which one did you use?

**Comment by chris001** [comment]
How much RAM your server have?

**Comment by IlirBajrami** [comment]
> Did you use a very small droplet? Which one did you use?

i used the smallest one. $5 a month

**Comment by IlirBajrami** [comment]
> How much RAM your server have?

/ 1 GB Memory / 25 GB Disk / FRA1 - Ubuntu 20.04 (LTS) x64

**Comment by jovar-dev** [comment]
I had the same problem few minutes ago. I tried install Odoo 12 in a droplet with 1GB of RAM. To fix it, you need to create a droplet with at least 2 GB. With the Odoo 13 script the same does not happen, it can be installed normally in a droplet with 1GB of RAM.

**Comment by IlirBajrami** [comment]
> I had the same problem few minutes ago. I tried install Odoo 12 in a droplet with 1GB of RAM. To fix it, you need to create a droplet with at least 2 GB. With the Odoo 13 script the same does not happen, it can be installed normally in a droplet with 1GB of RAM.

ironically i was installing odoo13 :) didnt have time to try with bigger droplet yet. will report it as soon as i try.

**Comment by Yenthe666** [comment]
Yeah the issue is known on DO when you use droplets of 1GB of RAM. It needs 2GB at least or it will often fail on the deployment of the wheel part.

**Comment by fourthcore** [comment]
Issues running in UBUNTO 20 Server, after installation refuse to connect?

- Firewall already set to allow,
- Service required all are running.

Kindly advice.....

**Comment by MihranThalhath** [comment]
Installing lxml as a dist package should fix this issue on instance with less RAM. Even though 1 GB RAM is less, a very small business might only need that.

**Comment by Yenthe666** [comment]
Don't ever take a 1GB RAM server, it's bound to fail sooner or later :)

**Comment by topeshittu** [comment]
Hello, After installing the enterprise version, i keep getting the community version instead. Please what could be wrong. I modified the script and set is Enterprise to be true. It asked for my github details while installing to, please help.

**Comment by gikwereresteven** [comment]
Hello
How I can solve the problem of postgresql
activate(exited) I use scripts in few days was working well but now database in of because of this activate(exited)

**Comment by hilarak** [comment]
**solution for wheel LXML setup issue**
It possibly occurs while any conflicts in python versions and probably their headers are not installed.
try to update python-dev for the related python version that you are using for ODOO.
eg: **sudo apt-get install python3.6-dev** where I have 3.6,3.7,3.8 versions in Ubuntu 20.04

**Comment by kyotr** [comment]
I never had issue while using odoo script on small droplet 1 GB Memory / 25 GB Disk. i always add swap file maybe thats the reason.

```
sudo fallocate -l 2g /mnt/2GiB.swap
sudo chmod 600 /mnt/2GiB.swap
sudo mkswap /mnt/2GiB.swap
sudo swapon /mnt/2GiB.swap
echo '/mnt/2GiB.swap swap swap defaults 0 0' | sudo tee -a /etc/fstab
```

i just finished installing one with no issue (except wkhtmltopdf version issue)

fixed with:
```
sudo wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
sudo dpkg -i wkhtmltox_0.12.5-1.bionic_amd64.deb
sudo apt install –f
```

**Comment by vijaygwala** [comment]
very usefull it worked

**Comment by kprempeh** [comment]
after creating my droplet and installing odoo on digital ocean, i cant print because of this error, Unable to find Wkhtmltopdf on this system. The report will be shown in html. i need help generation pdf. i tried the solution from @kyotr  but still issue persist.

**Comment by MuhammedNoufalI** [comment]
Can we solve the issue by adding more amount of swap space @Yenthe666

**Comment by Yenthe666** [comment]
More RAM always does the trick :)

**Comment by moemehdawi** [comment]
@Yenthe666 I used the script to install odoo 16 on amazon was tried a lot and always I am getting 502 bad gateway error, any advise ?

**Comment by MuhammedNoufalI** [comment]
@vodocloud Please provide log,

**Comment by moemehdawi** [comment]
> [@vodocloud](https://github.com/vodocloud) Please provide log,

here is the nginx configurations 

server {

  # set proper server name after domain set
server_name crm.pixelryt.com;

  # Add Headers for odoo proxy mode
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Real-IP $remote_addr;
add_header X-Frame-Options "SAMEORIGIN";
add_header X-XSS-Protection "1; mode=block";
proxy_set_header X-Client-IP $remote_addr;
proxy_set_header HTTP_X_FORWARDED_HOST $remote_addr;

  #   odoo    log files
access_log  /var/log/nginx/odoo-access.log;
error_log/var/log/nginx/odoo-error.log;

  #   increase    proxy   buffer  size
proxy_buffers   16  64k;
proxy_buffer_size   128k;

proxy_read_timeout 900s;
proxy_connect_timeout 900s;
proxy_send_timeout 900s;

  #   force   timeouts    if  the backend dies
proxy_next_upstream error   timeout invalid_header  http_500    http_502
http_503;

types {
text/less less;
text/scss scss;
}
#   enable  data    compression
gzip    on;
gzip_min_length 1100;
gzip_buffers    4   32k;
gzip_types  text/css text/less text/plain text/xml application/xml application/json application/javascript application/pdf image/jpeg image/png;
gzip_vary   on;
client_header_buffer_size 4k;
large_client_header_buffers 4 64k;
client_max_body_size 0;

location / {
proxy_pass    http://127.0.0.1:8069;
    # by default, do not forward anything
proxy_redirect off;
}

location /longpolling {
proxy_pass http://127.0.0.1:8072;
}

location ~* .(js|css|png|jpg|jpeg|gif|ico)$ {
expires 2d;
proxy_pass http://127.0.0.1:8069;
add_header Cache-Control "public, no-transform";
}

  # cache some static data in memory for 60mins.
location ~ /[a-zA-Z0-9_-]*/static/ {
proxy_cache_valid 200 302 60m;
proxy_cache_valid 4041m;
proxy_buffering    on;
expires 864000;
proxy_pass    http://127.0.0.1:8069;
}

listen 443 ssl; # managed by Certbot
ssl_certificate /etc/letsencrypt/live/crm.pixelryt.com/fullchain.pem; # managed by Certbot
ssl_certificate_key /etc/letsencrypt/live/crm.pixelryt.com/privkey.pem; # managed by Certbot
include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
if ($host = crm.pixelryt.com) {
return 301 https://$host$request_uri;
} # managed by Certbot


listen 80;
server_name crm.pixelryt.com;
return 404; # managed by Certbot


}





Log 

2025/04/15 16:01:27 [error] 31668#31668: *7 connect() failed (111: Connection refused) while connecting to upstream, client:
 (My Personal IP ), server: crm.pixelryt.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8069/", host: "crm.pixelryt.com"
