### ISSUE TITLE
no CSS after installing Odoo11 Enterprise 

### ISSUE THREAD

**Issue by khansch** [Yenthe666/InstallScript#58]
After installing with your script on ubuntu 16.04 I get no css and the -u all attempt did not work. the server just does not do anything after the command. 

![image](https://user-images.githubusercontent.com/32635870/31508784-74a5754e-af7f-11e7-823d-e483f69f67fb.png)

2017-10-12 15:01:25,394 17118 INFO ? odoo: database: default@default:default
2017-10-12 15:01:25,400 17118 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8070
2017-10-12 15:01:25,451 17118 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2017-10-12 15:01:36,621 17118 INFO ? odoo.http: Generating nondb routing
2017-10-12 15:01:36,705 17118 INFO ? werkzeug: 93.237.107.48 - - [12/Oct/2017 15:01:36] "GET /web/database/selector HTTP/1.1" 200 -
2017-10-12 15:01:36,761 17118 INFO ? werkzeug: 93.237.107.48 - - [12/Oct/2017 15:01:36] "GET /web/static/lib/bootstrap/css/bootstrap.css HTTP/1.1" 404 -
2017-10-12 15:01:36,762 17118 INFO ? werkzeug: 93.237.107.48 - - [12/Oct/2017 15:01:36] "GET /web/static/lib/fontawesome/css/font-awesome.css HTTP/1.1" 404 -
2017-10-12 15:01:36,762 17118 INFO ? werkzeug: 93.237.107.48 - - [12/Oct/2017 15:01:36] "GET /web/static/lib/bootstrap/js/tooltip.js HTTP/1.1" 404 -
2017-10-12 15:01:36,762 17118 INFO ? werkzeug: 93.237.107.48 - - [12/Oct/2017 15:01:36] "GET /web/static/lib/jquery/jquery.js HTTP/1.1" 404 -
2017-10-12 15:01:36,763 17118 INFO ? werkzeug: 93.237.107.48 - - [12/Oct/2017 15:01:36] "GET /web/static/lib/bootstrap/js/modal.js HTTP/1.1" 404 -
2017-10-12 15:01:36,777 17118 INFO ? werkzeug: 93.237.107.48 - - [12/Oct/2017 15:01:36] "GET /web/static/lib/bootstrap/js/dropdown.js HTTP/1.1" 404 -
2017-10-12 15:01:36,800 17118 INFO ? werkzeug: 93.237.107.48 - - [12/Oct/2017 15:01:36] "GET /web/static/lib/bootstrap/js/modal.js HTTP/1.1" 404 -
2017-10-12 15:01:36,812 17118 INFO ? werkzeug: 93.237.107.48 - - [12/Oct/2017 15:01:36] "GET /web/static/src/img/logo2.png HTTP/1.1" 404 -
2017-10-12 15:01:36,836 17118 INFO ? werkzeug: 93.237.107.48 - - [12/Oct/2017 15:01:36] "GET /web/static/lib/bootstrap/js/tooltip.js HTTP/1.1" 404 -
2017-10-12 15:01:36,873 17118 INFO ? werkzeug: 93.237.107.48 - - [12/Oct/2017 15:01:36] "GET /web/static/lib/bootstrap/js/dropdown.js HTTP/1.1" 404 -
2017-10-12 15:01:36,919 17118 INFO ? werkzeug: 93.237.107.48 - - [12/Oct/2017 15:01:36] "GET /web/static/src/img/logo2.png HTTP/1.1" 404 -
2017-10-12 15:01:40,790 17118 INFO ? werkzeug: 93.237.107.48 - - [12/Oct/2017 15:01:40] "GET /web/database/selector HTTP/1.1" 200 -
2017-10-12 15:01:40,829 17118 INFO ? werkzeug: 93.237.107.48 - - [12/Oct/2017 15:01:40] "GET /web/static/lib/fontawesome/css/font-awesome.css HTTP/1.1" 404 -
2017-10-12 15:01:40,851 17118 INFO ? werkzeug: 93.237.107.48 - - [12/Oct/2017 15:01:40] "GET /web/static/lib/bootstrap/js/modal.js HTTP/1.1" 404

**Comment by Yenthe666** [comment]
Thanks for your report! What happens when you add ?debug=assets to the URL? Does the Odoo fully render then?

**Comment by khansch** [comment]
no, no changes at all. Its weird.

**Comment by chris001** [comment]
The  404 error is possibly because of incorrect ownership of the static CSS files.
`chown -R odoo. *` should fix it.

**Comment by Yenthe666** [comment]
They should be correct by default with the script though..

**Comment by vigermam** [comment]
as I mentioned in the other issue. you kinda need to tick the system to get it working. #55 , look my notes [there](https://github.com/Yenthe666/InstallScript/issues/55#issuecomment-335109572).

**Comment by Yenthe666** [comment]
@vigermam that is a workaround, not a solution to the issue of the script or the source though. I'd like to pinpoint that in order to fix it for everybody.

**Comment by vigermam** [comment]
@Yenthe666 i just thought that might help anyone need to get it working at this very moment. or might help you to find where things might be broken. Thanks so much for the great work! 👍

**Comment by Yenthe666** [comment]
Absolutely! 😉 I hope I can pinpoint the source problem soon. Thank you!

**Comment by khansch** [comment]
Awesome guys... thanks for the commitment! Very much appreciated!!! Thanks a lot. Keep us updated.

**Comment by Yenthe666** [comment]
We'll get there! I believe the dependencies are a bit different on the different Linux flavours. Some of them have dependencies out of the box and some don't. This problem looks bigger in the latest version than the other ones.

**Comment by khansch** [comment]
Thanks Yenthe. Keep me updated. I wonder why Odoo doesn't have a skript or a howto to install the EE - the version that makes them money.......

**Comment by Yenthe666** [comment]
@khansch I guess they have this: https://www.odoo.com/documentation/11.0/setup/install.html
I don't really like it but I may be biased 😉

**Comment by khansch** [comment]
This howto sucks. already the link to the download of enterprise edition does not work, even though I am a subscribed member to EE 11. So I hope you have a solution to the problem soon. 👍

**Comment by khansch** [comment]
Still no change. Tried another dependency, but no effect. Still no CSS. :-(

**Comment by chris001** [comment]
@Yenthe666 
Where are you getting the dependencies list from?
Is it from here?:
https://nightly.odoo.com/11.0/nightly/deb/Packages
```
Depends: init-system-helpers (>= 1.18~), python3-babel, python3-dateutil, python3-decorator, python3-docutils, python3-feedparser, python3-gevent, python3-html2text, python3-jinja2, python3-lxml, python3-mako, python3-mock, python3-ofxparse, python3-passlib, python3-pil, python3-psutil, python3-psycopg2, python3-pydot, python3-pyparsing, python3-pypdf2, python3-reportlab, python3-requests, python3-serial, python3-tz, python3-usb, python3-vatnumber, python3-werkzeug, python3-xlsxwriter, python3-yaml, python3:any (>= 3.3.2-2~), adduser, lsb-base, node-less, postgresql-client, python3-suds
Recommends: postgresql, python3-pyldap, python3-qrcode, python3-vobject
Conflicts: openerp, openerp-server, openerp-web, tinyerp-server
Replaces: openerp, openerp-server, openerp-web, tinyerp-server
```

**Comment by Yenthe666** [comment]
From the Github repository its requirements (https://github.com/odoo/odoo/blob/11.0/requirements.txt)

**Comment by chris001** [comment]
OK, maybe odoo team made a tiny mistake, maybe there is a dependency in the debian `Packages` list which was left out, by mistake, from the python `requirements.txt`.  It's a small chance, but it's possible, so it should be double checked, just to be sure.

**Comment by khansch** [comment]
Guys, do you have any news? Still no way to get odoo11 installed properly. Thanks for your help.

**Comment by Yenthe666** [comment]
I don't have access to a computer at the moment. It is high on my priority list so I'll setup new servers with new tests this monday or tuesday. Sorry for the delay guys.

**Comment by Yenthe666** [comment]
Hi all,

I've made a new Ubuntu 16.04.3 server and ran both the community and the enterprise installation script. Both worked fine out of the box without any extra configuration or installations.
So either there is another version that gives problem or I'm really missing something.

**Comment by chris001** [comment]
@khansch 
(From issue #55 )
What happens when you do:
1. `sudo service odoo-server stop` (just to be sure nothing is running)
2. `cd /odoo/odoo-server`
3. `sudo su odoo`
4. `./odoo-bin -c /etc/odoo-server.conf`

**Comment by khansch** [comment]
@Yenthe666  Is the chat in your installation working correctly? We got odoo installed by our technical partner, but the chat it not working properly. If you type something in, it does not appear. If you refresh the browser, it appears. 

Thanks for your help.

**Comment by chris001** [comment]
@khansch 
Try chat on https://demo2.odoo.com/web#home for comparison.

**Comment by khansch** [comment]
hey chris, URL not found. 
I mean the chat inside of odoo. Thanks for your help!

**Comment by chris001** [comment]
@khansch 
What I meant is, try out the chat on the "Odoo Free Trial" and see if that works properly in your browser - without refreshing your browser page.
https://accounts.odoo.com/trial

**Comment by Yenthe666** [comment]
Indeed - try to reproduce it on a runbot or official instance. This could also be a configuration issue with SSL / Nginx forwarding for example.

**Comment by TornikeOdikadze** [comment]
I installed Odoo11 by package installers on CentOS7.
Css is not working after logging in.

**Comment by chris001** [comment]
@TornikeOdikadze 
1. Is it community or enterprise?
2. Post output from running install script?
3. Post logs while running (see comment above 27 days ago for how to)?

**Comment by alexx-alexx** [comment]
asas

**Comment by alexx-alexx** [comment]
For those how did the trick... Why not to share .ova of VM?
Script doesn't work. No css.

**Comment by chris001** [comment]
@alexx-alexx @TornikeOdikadze 
1. What happens when you add `?debug=assets` to the URL in the address line of the browser? Does the Odoo 11 fully render the CSS then?
2. What happens when you start Odoo 11 server this way, and watch the terminal for errors:
```
sudo service odoo-server stop # just to be sure odoo service stops
cd /odoo/odoo-server
sudo su odoo
./odoo-bin -c /etc/odoo-server.conf
```

Post back your results.

**Comment by liao0007** [comment]
Same problem here, Odoo 11 community edition.

installed from package on Ubuntu, tested without proxying.
All css files except few are not able to load properly, giving out 404 and no error in odoo-server.log.

![screen shot 2018-02-02 at 18 08 46](https://user-images.githubusercontent.com/8678521/35727874-a0ca3574-0844-11e8-851c-4546f30e93fc.png)

**Comment by chris001** [comment]
@liao0007 
Which URL you download install script from

**Comment by liao0007** [comment]
@chris001

I installed via package manager. 

“apt-get install odoo” following the official installation guild. 

I also tried to install via source by pulling latest version from github, with same problem.  

It could by something wrong with the system environment but I don’t know where to trace.

**Comment by chris001** [comment]
@liao0007 
Can you 
1. remove the odoo installed via package manager,
2. remove the odoo installed via source from github,
3. Install with my "big update" install script:
```
cd ~
rm odoo_install.sh
wget https://github.com/chris001/InstallScript/raw/patch-2/odoo_install.sh
chmod +x odoo_install.sh
./odoo_install.sh
```
4. verify that odoo-server service is status (running).
5. open another terminal, to watch for errors in system environment with this command:
```
tail -f /var/log/odoo/odoo-server
```

**Comment by liao0007** [comment]
@chris001 

It helps, thank you.

I think virtualenv did the work.

**Comment by aliomattux** [comment]
Just wanted to throw in my success. I had this same issue and it was because I declared an invalid folder path for an additional addon directory for extra modules. I created the directory and everything works. It seems like when an initial request is made to the server it validates the existence of all addons path and fails silently

**Comment by chris001** [comment]
@aliomattux 
This is true.  When there's an non-existent directory in the `addons_path`, Odoo 11 fails to produce any output on the user's browser at runtime.
This is an Odoo bug that should be fixed.
When there's a non-existent directory in the linux path, the linux kernel doesn't fail.

**Comment by FlyingPigSolutions** [comment]
@chris001 
Hello Chris,
I opened an issue that look similar [#23468](https://github.com/odoo/odoo/issues/23468) and after trying so many things to make it work without success:
- giving rights `chown -R `
- update python to 3.6 version
- postgresql config from md5 to trust
- checked my paths (well it was working perfectly fine for 2 month and we didn't change it) in `odoo-server.conf`

I am thinking of reinstalling my Odoo.
However, I have a database running for 2 months of data. I wouldn't like to loose it.
Can I follow the step mentioned and reinstall independently of the database ? 
`cd ~
rm odoo_install.sh
wget https://github.com/chris001/InstallScript/raw/patch-2/odoo_install.sh
chmod +x odoo_install.sh
./odoo_install.sh
`

**Comment by chris001** [comment]
@FlyingPigSolutions 
* To be safe, you really should save a backup file containing your data currently stored in the odoo database, and upload it to a secure cloud account on a different machine than the odoo server, doing this will protect your data, in case of an unexpected event occurs: 
`sudo pg_dump -U user_name database_name > backup_file`
* This install script only installs (or reinstalls) the app and all its required dependencies + optional nginx web server + secure LE HTTPS cert.
* To answer your question, when you run the install script again, your data should remain untouched, the only thing updated on the database is the normal "database schema update" to match the new version of the Odoo code.
* Depending on if your `odoo_install.sh` is new enough, you can update itself to the newest version, in just one command: `./odoo_install.sh --self-update`
* EDIT: You can also upgrade only the odoo code, with: `./odoo_install.sh --upgrade`

**Comment by FlyingPigSolutions** [comment]
Thank you @chris001 
Very useful to know although in my case it didn't do the trick.
>  just tried
Unless I missed a restart action (I'll try to reboot the server too)
Problem still running unfortunately for me but really appreciate your detailed help.

**Comment by FlyingPigSolutions** [comment]
@chris001 Still trying to figure it out my issue that might be related to this one.

Here is my result:

> odoo@DOMAIN:~/odoo-server$ ./odoo-bin -c /etc/odoo-server.conf
> Traceback (most recent call last):
>   File "./odoo-bin", line 8, in <module>
>     odoo.cli.main()
>   File "/odoo/odoo-server/odoo/cli/command.py", line 60, in main
>     o.run(args)
>   File "/odoo/odoo-server/odoo/cli/server.py", line 175, in run
>     main(args)
>   File "/odoo/odoo-server/odoo/cli/server.py", line 124, in main
>     odoo.tools.config.parse_config(args)
>   File "/odoo/odoo-server/odoo/tools/config.py", line 334, in parse_config
>     odoo.netsvc.init_logger()
>   File "/odoo/odoo-server/odoo/netsvc.py", line 95, in init_logger
>     resetlocale()
>   File "/odoo/odoo-server/odoo/tools/translate.py", line 1183, in resetlocale
>     for ln in get_locales():
>   File "/odoo/odoo-server/odoo/tools/translate.py", line 1152, in get_locales
>     lang = locale.getdefaultlocale()[0]
>   File "/usr/lib/python3.5/locale.py", line 558, in getdefaultlocale
>     return _parse_localename(localename)
>   File "/usr/lib/python3.5/locale.py", line 486, in _parse_localename
>     raise ValueError('unknown locale: %s' % localename)
> ValueError: unknown locale: UTF-8
> 

I'll try also what you suggested above early february

**Comment by chris001** [comment]
@FlyingPigSolutions Looks like your installation is displaying an `unknown locale UTF-8` issue.
My "big update" version of `odoo_install.sh` script should fix this `locale` issue.
Try and report back your results here.

**Comment by FlyingPigSolutions** [comment]
Hello @chris001  I tried to send you a mail through your website but the contact page wasn't working.
Can you send me your email please. I would like to ask you something but not in public.

**Comment by chris001** [comment]
@FlyingPigSolutions 
Contact is firstname (at) (website dot com)

**Comment by maximilienvicidomini06** [comment]
Hello All I still have the issue could someone help me ? 
<img width="1137" alt="capture d ecran" src="https://user-images.githubusercontent.com/39404071/40315010-783bdee8-5d1a-11e8-8837-4d9d50633c5e.png">

**Comment by xabispacebiker** [comment]
I had the same problem and in my case was a wrong addons_path in /etc/odoo/odoo.conf.

**Comment by AbdulghaniFawzi** [comment]
> This could also be a configuration issue with SSL / Nginx forwarding for example.

if ssl forwarding did this error, what will be the solution 
@Yenthe666

**Comment by Yenthe666** [comment]
Depends on what the issue is, I'm totally going to guess it is due to a missing dependency or wrong `addons_path` though. I'd check those two first. I've never had these issues and installed dozens of Odoo's.

**Comment by AbdulghaniFawzi** [comment]
i  already have this error  before enable ssl all things is good, after enable ssl with apache  this error appear
if i return to the first point by disable ssl the error still
@Yenthe666

**Comment by Yenthe666** [comment]
Then your configs are wrong basically

**Comment by AbdulghaniFawzi** [comment]
@Yenthe666 
can you give me the standard steps  to check my configs

**Comment by Yenthe666** [comment]
Sorry but I never use `apache`, it is really outdated. You should look at better alternatives such as `Nginx` (where loads of tutorials and info can be found for too) :)

**Comment by oberak** [comment]
I got the same problem on Ubuntu 18.04 & Odoo 12.0
in my case i didn't make custom addon folder.

In console.
2018-12-21 06:33:06,994 4448 INFO ? odoo: addons paths: ['/opt/odoo/.local/share/Odoo/addons/12.0', '/opt/odoo/odoo12/addons', '/opt/odoo/odoo12-custom-addons', '/opt/odoo/odoo12/odoo/addons']

but I did't make '/opt/odoo/odoo12-custom-addons'
After creating the folder and restarting it works fine.
I don't know why...
