### ISSUE TITLE
Script hangs on cat <<EOF > ~/$OE_CONFIG line

### ISSUE THREAD

**Issue by Yenthe666** [Yenthe666/InstallScript#6]
Some users seem to run stuck on that line.
Could not reproduce issue myself.. Reports can be found on my blogpost: http://www.odoo.yenthevg.com/installing-odoo-9-on-ubuntu-14-04/

**Comment by Yenthe666** [comment]
@tvibliani,

I've had this issue reported about 3 times now. I can't reproduce this in any way though.. Any idea from your side? Could you give this a test too?

**Comment by effelle** [comment]
Sorry for the delay Yenthe, busy day.

The script on Github doesn't hangs and install fine, but the one on your blog and the one here in Github are different. Beside some spacing between the lines, using meld (on repos if you need it) I found just a line that keep my attention with a different syntax:

```
odoo_install.sh on Github: pid=\`cat \$PIDFILE\`
odoo_install.sh on Blog: pid=`cat \$PIDFILE`
```
![odoo_install_diff](https://cloud.githubusercontent.com/assets/7702766/10265344/b5a5b68a-6a03-11e5-8bd6-561e171ce026.png)

Nothing else. Perhaps some text formatting issue? 
Pull out the script from the blog and point a link with the direct download. ;)

Just a side note, why download an entire branch? Normal user need just the first level, I propose something "classic" like:
sudo git clone https://www.github.com/odoo/odoo --depth 1 --branch  $OE_VERSION --single-branch . $OE_HOME_EXT/

**Comment by Yenthe666** [comment]
@effelle,

Thanks a lot for having a look at this and comparing both versions, I didn't even think about doing that.
You're right, the interpreter from my blog changed the content on the cat line.. Missing one \ made it not work.
I've added an extra line on my blog advising people to take the code from Github, but I left the script in it as alternative.
I don't have enough time to test my blog script now but I <b>think</b> that everything should be fixed now. I'll try to test this later today but I don't have enough time now.

As for that sidenote: what do you mean about the entire branch? Do you mean that I make /odoo/odoo-server/ for example?

Thanks for the help & feedback! :+1:

**Comment by Yenthe666** [comment]
@effelle,

Made a new, clean, Ubuntu VM and ran the script with the code from my blog without any problems. I think it is fixed now! Could you give this a try to if you have the time please? :+1:

**Comment by effelle** [comment]
Yep. It's working now. But I strongly advice you to guide your guests to download the sh directly from github to avoid future issues.

About the branch, on your script you are downloading the whole branch but you don't need it for a stock install.
Some time ago I found a guide to install Odoo 8 @ http://www.theopensourcerer.com/2014/09/how-to-install-openerp-odoo-8-on-ubuntu-server-14-04-lts/

and I've seen they let the user install just the first level of the branch (the latest) with

```git clone https://www.github.com/odoo/odoo --depth 1 --branch 8.0 --single-branch .```

Do a spin to your script with this configuration for git clone and you'll see, beside a faster download, that you don't need the whole branch. At least for V8 worked fine. :)

**Comment by Yenthe666** [comment]
@effelle,

Thanks for testing and giving me feedback.
About the branch: what exactly is the difference between a full depth and a --depth 1? I did notice the speed is a lot faster but what exactly is different? Does it have any disadvantages to use -- depth 1?

**Comment by tvibliani** [comment]
@Yenthe666 

I think @effelle is right, version on the blog is different from the one here, and he outlined correctly that it should be
```Bash
pid=\`cat \$PIDFILE\`
```
instead of 
```Bash
pid=`cat \$PIDFILE`
```
-as it is here, on github. It was part of pull request I made and it's included in mainstream now. it was commited here: 0e1cc7b9b3e318c84d1c656ffbf299d50cd57dc6

the difference is that in first case the \` characters are escaped using \ and it'll put the text line "pid=`cat $PIDFILE`" as is in the init script created, but in second case it'll put "pid=" + result of cat \$PIDFILE, which is incorrect even if it'll run, and it'll hung on this line if \$PIDFILE  file does not exists for the moment of execution of installer script. 
Please update script at the blog to have synchronized it with github version

**Comment by effelle** [comment]
My bad, I checked diff with the wrong script... The error is still present
on the blog. Sorry for that.
Seems wordpress is not able to escape the " ` " correclty.

About git: downloading with --depth 1 option will pull just the last level
of the branch without the history of the various commits, useful just if
you are deeply involved in development.
For a repository like Odoo this will make a BIG difference in terms of
space and time for the average user but you will have just the latest
version.
I allways download with --level option and did not see any difference on V8
on my dev machines when I work on my modules. Perhaps you should speak with
some Odoo devs and see what they think about it.

F.

**Comment by sebastian-code** [comment]
@Yenthe666 for the --depth 1 option, what it does is to download the most recent status of the repository, and the most recent version of every file inside it, taking away the chance to checkout the previous commits, something you're not going to need in production.

**Comment by Yenthe666** [comment]
@sebastian-code thanks a lot for providing me with more information. my Github knowledge is rather limited. I've given it a testrun with --depth 1 and the speed was quite better. I agree that this has more benefits then downsides so I'll merge that in!

**Comment by Yenthe666** [comment]
@tvibliani why don't we actually go back to one script? We could make an if/else for the version specific libs too? Means that the script is even easier to use for people with very little knowledge.
Something like:
```
OE_VERSION="8.0"
if [ $OE_VERSION = "9.0" ]; then
  echo -e "\n--- V9: Install other required packages"
  sudo apt-get install node-clean-css -y
  sudo apt-get install node-less -y
  sudo apt-get install python-gevent -y
else
  echo "Installing Odoo $OE_VERSION - no need for V9 libraries"
fi
```

Do you see any benefits or downsides in this?

**Comment by effelle** [comment]
Agree. But I didn't see any issues installing the extra packages  on a V8
setup. Let me have a spin on a VM and I'll check again.

**Comment by tvibliani** [comment]
@Yenthe666 Nice approach :+1: actually we can support installation of both, 8.0 and 9.0 from a single script... we'll benefit from about 50% reduced code to maintain, less code - less bugs, and about two times better tested script (as the same code will be tested for both versions)...  a downside I see is that user will have to adapt `OE_VERSION` variable to 8.0 or 9.0, if we'll not have separated scripts, rather then simply download/ran corresponding one, but that's probably not a big deal

**Comment by tvibliani** [comment]
@effelle I agree with you, extra package installation is not actually an issue as such, but avoiding extra package installation is nice to have, in terms of installation time / disk space usage... So it may be considered as enhancement

**Comment by sebastian-code** [comment]
I would say than, perhaps, there is room for the creation an small questionnaire at the beginning of the script to ask for some input from the user, passwords, user name, version to install and any other additional information than can be personalized.

**Comment by effelle** [comment]
I was thinking (and writing) the very same thing right now. I just didn't
wrote here because we should open a new ticket for that.
@Yenthe666 you could consider it as a step two for a definitive install
script. ;)

**Comment by Yenthe666** [comment]
@effelle, @tvibliani and @sebastian-code you guys are all welcome to think out loud and give suggestions!
I've added an issue for this where we can think out loud about what would be awesome to have, what needs to be improved, ... See https://github.com/Yenthe666/InstallScript/issues/10

```
I would say than, perhaps, there is room for the creation an small questionnaire at the beginning of the script to ask for some input from the user, passwords, user name, version to install and any other additional information than can be personalized.
```
This is pretty much in the script already, see https://github.com/Yenthe666/InstallScript/blob/9.0/odoo_install.sh#L19-L32
